#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if n >= 0 and n <= 100:
        p = n % 2
        if p == 0:
            if n > 1 and n <= 5:
                print ("Not Weird")
            if n > 5 and n <= 20:
                print ("Weird")
            if n > 20:
                print ("Not Weird")
        elif p == 1:
            print ("Weird")
            
            
